- name: Install Applications on macOS
  hosts: localhost
  connection: local
  become: false  # No sudo needed for Homebrew

  roles:
    - elliotweiser.osx-command-line-tools


  vars:
    brew_cask_apps:
      - visual-studio-code
      - curseforge
      - firefox

    brew_packages:
      - git
      - wget
      - node
      - python3
      - ansible

    install_homebrew_if_missing: true
    upgrade_homebrew_packages: true


  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: "Homebrew is not installed. Set install_homebrew_if_missing to true to install it."
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      args:
        executable: /bin/bash
      when: not homebrew_check.stat.exists


  tasks:

    - name: Installing Homebrew Cask Apps
      homebrew_cask:
        name: "{{ brew_cask_apps }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        name: "{{ item }}"
        state: latest
      loop: "{{ brew_packages }}"
      register: result
      until: result is successful
      when:
        - homebrew_check.stat.exists
        - upgrade_homebrew_packages