choco install git -y
choco install vscode -y
choco install googlechrome -y
choco install 7zip -y
choco install firefox -y
choco install bambustudio -y
choco install microsoft-teams.install -y
choco install epicgameslauncher -y
choco install discord -y
choco install steam -y
choco install nvidia-app -y
choco install winscp -y
choco install openoffice -y
choco install microsoft-office-deployment -y
choco install mingw -y
choco install imageglass -y